### ISSUE TITLE
Issue in running Python Demo on occlum/occlum:0.15.1-ubuntu18.04 docker container

### ISSUE THREAD

**Issue by tahashmi** [occlum/occlum#124]
I have followed all the steps mentioned in [Readme](https://github.com/occlum/occlum/tree/master/demos/python) for Python Alpine export to Occlum.
Running python demo for [Occlum docker container](occlum/occlum:0.15.1-ubuntu18.04) incurs the following issue:

```
root@49c06e6ab08d:~# cd demos/python/
root@49c06e6ab08d:~/demos/python# ./run_python_on_occlum.sh 
/root/demos/python/occlum_instance initialized as an Occlum instance
Enclave sign-tool: /opt/intel/sgxsdk/bin/x64/sgx_sign
Enclave sign-key: /opt/occlum/etc/template/Enclave.pem
SGX mode: HW
Building new image...
[+] Home dir is /root
[-] Open token file /root/enclave.token error! Will create one.
[+] Init Enclave Successful 485331304450!
Building libOS...
EXPORT => OCCLUM_BUILTIN_CONF_FILE_MAC = 5d-bf-bb-0e-06-ca-77-f9-43-43-3a-d3-68-9a-9b-af
EXPORT => OCCLUM_BUILTIN_VM_USER_SPACE_SIZE = 335544320
Signing the enclave...
<EnclaveConfiguration>
    <ProdID>0</ProdID>
    <ISVSVN>0</ISVSVN>
    <StackMaxSize>1048576</StackMaxSize>
    <HeapMaxSize>150994944</HeapMaxSize>
    <TCSNum>32</TCSNum>
    <TCSPolicy>1</TCSPolicy>
    <DisableDebug>0</DisableDebug>
    <MiscSelect>0</MiscSelect>
    <MiscMask>0xFFFFFFFF</MiscMask>
    <ReservedMemMaxSize>335544320</ReservedMemMaxSize>
    <ReservedMemMinSize>335544320</ReservedMemMinSize>
    <ReservedMemInitSize>335544320</ReservedMemInitSize>
    <ReservedMemExecutable>1</ReservedMemExecutable>
</EnclaveConfiguration>
tcs_num 32, tcs_max_num 32, tcs_min_pool 1
The required memory is 522752000B.
The required memory is 0x1f289000, 510500 KB.
Succeed.
Built the Occlum image and enclave successfully
occlum run /bin/python3.7 demo.py

/opt/occlum/build/bin/occlum: line 191:   185 Illegal instruction     (core dumped) RUST_BACKTRACE=1 "$instance_dir/build/bin/occlum-run" "$@"
root@49c06e6ab08d:~/demos/python#
```

**Comment by tahashmi** [comment]
Thanks for reply!

Yes, I just tried hello world program inside container. Its working:

```
tahmad@TUD256255:~$ sudo docker run -it --device /dev/isgx  occlum/occlum:0.15.1-ubuntu18.04
root@272068155fae:~# aesm_service[13]: [ADMIN]White List update requested
aesm_service[13]: The server sock is 0x55d0c0a51120
aesm_service[13]: [ADMIN]White list update request successful for Version: 79
^C
root@272068155fae:~# ls
demos
root@272068155fae:~# cd demos/
root@272068155fae:~/demos# cd hello_c
root@272068155fae:~/demos/hello_c# ./hello_world 
Hello World
root@272068155fae:~/demos/hello_c#
```

**Comment by tatetian** [comment]
Hi @tahashmi , I meant running the hello world program inside an SGX enclave on Occlum. What should be done is like the following
```
occlum new occlum_workspace
cd occlum_workspace
cp ../hello_world image/bin
occlum build
occlum run /bin/hello_world
```

One common cause of an illegal instruction error is the miss of `enable_rdfsbase` kernel module. So make sure the kernel module is installed.

**Comment by tahashmi** [comment]
Hi @tatetian , Thanks. I just tried running hello world program inside an SGX enclave on Occlum as you advised. It seems this demo is also working fine. I have again installed `enable_rdfsbase`.
```
root@a39c97c3c93b:~/occlum_workspace# cp /root/demos/hello_c/hello_world image/bin
root@a39c97c3c93b:~/occlum_workspace# occlum build
Enclave sign-tool: /opt/intel/sgxsdk/bin/x64/sgx_sign
Enclave sign-key: /opt/occlum/etc/template/Enclave.pem
SGX mode: HW
Building new image...
[+] Home dir is /root
[-] Open token file /root/enclave.token error! Will create one.
[+] Init Enclave Successful 403726925826!
Building libOS...
EXPORT => OCCLUM_BUILTIN_CONF_FILE_MAC = f5-47-0e-90-78-6a-82-f6-be-1f-fc-68-06-27-97-eb
EXPORT => OCCLUM_BUILTIN_VM_USER_SPACE_SIZE = 268435456
Signing the enclave...
<EnclaveConfiguration>
    <ProdID>0</ProdID>
    <ISVSVN>0</ISVSVN>
    <StackMaxSize>1048576</StackMaxSize>
    <HeapMaxSize>33554432</HeapMaxSize>
    <TCSNum>32</TCSNum>
    <TCSPolicy>1</TCSPolicy>
    <DisableDebug>0</DisableDebug>
    <MiscSelect>0</MiscSelect>
    <MiscMask>0xFFFFFFFF</MiscMask>
    <ReservedMemMaxSize>268435456</ReservedMemMaxSize>
    <ReservedMemMinSize>268435456</ReservedMemMinSize>
    <ReservedMemInitSize>268435456</ReservedMemInitSize>
    <ReservedMemExecutable>1</ReservedMemExecutable>
</EnclaveConfiguration>
tcs_num 32, tcs_max_num 32, tcs_min_pool 1
The required memory is 338202624B.
The required memory is 0x14289000, 330276 KB.
Succeed.
Built the Occlum image and enclave successfully
root@a39c97c3c93b:~/occlum_workspace# occlum run /bin/hello_world
Hello World
root@a39c97c3c93b:~/occlum_workspace# 

```

Today, I have repeated all the procedure again for creating alp container and running python demo in enclave and here is the log:

```
root@527563d038a1:~# cd demos/
root@527563d038a1:~/demos# cd python/
root@527563d038a1:~/demos/python# ./run_python_on_occlum.sh 
/root/demos/python/occlum_instance initialized as an Occlum instance
Enclave sign-tool: /opt/intel/sgxsdk/bin/x64/sgx_sign
Enclave sign-key: /opt/occlum/etc/template/Enclave.pem
SGX mode: HW
Building new image...
[+] Home dir is /root
[-] Open token file /root/enclave.token error! Will create one.
[+] Init Enclave Successful 425201762306!
Building libOS...
EXPORT => OCCLUM_BUILTIN_CONF_FILE_MAC = 72-ba-01-1b-b1-da-e5-58-c0-6b-91-bd-ad-7f-6e-dd
EXPORT => OCCLUM_BUILTIN_VM_USER_SPACE_SIZE = 335544320
Signing the enclave...
<EnclaveConfiguration>
    <ProdID>0</ProdID>
    <ISVSVN>0</ISVSVN>
    <StackMaxSize>1048576</StackMaxSize>
    <HeapMaxSize>150994944</HeapMaxSize>
    <TCSNum>32</TCSNum>
    <TCSPolicy>1</TCSPolicy>
    <DisableDebug>0</DisableDebug>
    <MiscSelect>0</MiscSelect>
    <MiscMask>0xFFFFFFFF</MiscMask>
    <ReservedMemMaxSize>335544320</ReservedMemMaxSize>
    <ReservedMemMinSize>335544320</ReservedMemMinSize>
    <ReservedMemInitSize>335544320</ReservedMemInitSize>
    <ReservedMemExecutable>1</ReservedMemExecutable>
</EnclaveConfiguration>
tcs_num 32, tcs_max_num 32, tcs_min_pool 1
The required memory is 522752000B.
The required memory is 0x1f289000, 510500 KB.
Succeed.
Built the Occlum image and enclave successfully
occlum run /bin/python3.7 demo.py
thread '<unnamed>' panicked at 'failed to read SgxFile: Os { code: 12, kind: Other, message: "Cannot allocate memory" }', src/fs/sefs/sgx_storage.rs:198:19
stack backtrace:
   0: <sgx_tstd::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   2: sgx_tstd::io::Write::write_fmt
   3: sgx_tstd::panicking::default_panic_handler
   4: sgx_tstd::panicking::rust_panic_with_hook
   5: rust_begin_unwind
   6: core::panicking::panic_fmt
             at src/libcore/panicking.rs:111
   7: core::option::expect_none_failed
             at src/libcore/option.rs:1268
   8: <occlum_libos_core_rs::fs::sefs::sgx_storage::LockedFile as rcore_fs_sefs::dev::File>::read_at
   9: <rcore_fs_sefs::INodeImpl as rcore_fs::vfs::INode>::read_at
  10: <rcore_fs_unionfs::UnionINode as rcore_fs::vfs::INode>::read_at
  11: <rcore_fs_mountfs::MNode as rcore_fs::vfs::INode>::read_at
  12: <occlum_libos_core_rs::fs::inode_file::INodeFile as occlum_libos_core_rs::fs::file::File>::read_at
  13: occlum_libos_core_rs::vm::vm_manager::VMManager::mmap
  14: occlum_libos_core_rs::vm::process_vm::ProcessVM::mmap
  15: occlum_libos_core_rs::vm::do_mmap
  16: occlum_libos_core_rs::syscall::dispatch_syscall
  17: occlum_libos_core_rs::syscall::do_syscall
  18: occlum_syscall
  19: <unknown>
note: Some details are omitted, call backtrace::enable_backtrace() with 'PrintFormat::Full' for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 3
/opt/occlum/build/bin/occlum: line 191:   171 Illegal instruction     (core dumped) RUST_BACKTRACE=1 "$instance_dir/build/bin/occlum-run" "$@"
root@527563d038a1:~/demos/python# 
```
I have also changed demo.py inside Occlum demos in container to just print "Hello World!" instead of processing CSV file. Still same problem.

```
root@527563d038a1:~/demos/python# ./run_python_on_occlum.sh 
occlum run /bin/python3.7 demo.py
thread '<unnamed>' panicked at 'failed to read SgxFile: Os { code: 12, kind: Other, message: "Cannot allocate memory" }', src/fs/sefs/sgx_storage.rs:198:19
stack backtrace:
   0: <sgx_tstd::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   2: sgx_tstd::io::Write::write_fmt
   3: sgx_tstd::panicking::default_panic_handler
   4: sgx_tstd::panicking::rust_panic_with_hook
   5: rust_begin_unwind
   6: core::panicking::panic_fmt
             at src/libcore/panicking.rs:111
   7: core::option::expect_none_failed
             at src/libcore/option.rs:1268
   8: <occlum_libos_core_rs::fs::sefs::sgx_storage::LockedFile as rcore_fs_sefs::dev::File>::read_at
   9: <rcore_fs_sefs::INodeImpl as rcore_fs::vfs::INode>::read_at
  10: <rcore_fs_unionfs::UnionINode as rcore_fs::vfs::INode>::read_at
  11: <rcore_fs_mountfs::MNode as rcore_fs::vfs::INode>::read_at
  12: <occlum_libos_core_rs::fs::inode_file::INodeFile as occlum_libos_core_rs::fs::file::File>::read_at
  13: occlum_libos_core_rs::vm::vm_manager::VMManager::mmap
  14: occlum_libos_core_rs::vm::process_vm::ProcessVM::mmap
  15: occlum_libos_core_rs::vm::do_mmap
  16: occlum_libos_core_rs::syscall::dispatch_syscall
  17: occlum_libos_core_rs::syscall::do_syscall
  18: occlum_syscall
  19: <unknown>
note: Some details are omitted, call backtrace::enable_backtrace() with 'PrintFormat::Full' for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 3
/opt/occlum/build/bin/occlum: line 191:   631 Illegal instruction     (core dumped) RUST_BACKTRACE=1 "$instance_dir/build/bin/occlum-run" "$@"
root@527563d038a1:~/demos/python# 
```

**Comment by tatetian** [comment]
Hi @tahashmi , we have confirmed the issue and it has been fixed in the latest master.  See this [commit](https://github.com/occlum/occlum/commit/1463fb525a9a3a2e03fa22dafc3dfbe2a460f4c3). The problem is that for some reason, the LibOS does not have enough memory to run the Python program. So enlarging the value of `resource_limits.kernel_space_heap_size` in `Occlum.json` can fix the problem.

**Comment by tahashmi** [comment]
Thanks @tatetian for looking into this. But unfortunately I am still not able to run Python demo in Occlum.
I have changed the value of `resource_limits.kernel_space_heap_size` in `./run_python_on_occlum.sh` as shown below:

```
new_json="$(jq '.resource_limits.user_space_size = "320MB" |
                    .resource_limits.kernel_space_heap_size = "192MB" |
                    .process.default_mmap_size = "256MB"' Occlum.json)" && \
    echo "${new_json}" > Occlum.json
```
After running .`/run_python_on_occlum.sh `, it takes couple of minutes in  BLUE `occlum run /bin/python3.7 demo.py` and then shows the following log at my system.

```
root@6b2a0e64849b:~/demos/python# ./run_python_on_occlum.sh 
/root/demos/python/occlum_instance initialized as an Occlum instance
Enclave sign-tool: /opt/intel/sgxsdk/bin/x64/sgx_sign
Enclave sign-key: /opt/occlum/etc/template/Enclave.pem
SGX mode: HW
Building new image...
[+] Home dir is /root
[-] Open token file /root/enclave.token error! Will create one.
[+] Init Enclave Successful 420906795010!
Building libOS...
EXPORT => OCCLUM_BUILTIN_CONF_FILE_MAC = ab-7c-f7-22-ca-16-42-43-4b-40-7d-d9-d5-28-e7-b3
EXPORT => OCCLUM_BUILTIN_VM_USER_SPACE_SIZE = 335544320
Signing the enclave...
<EnclaveConfiguration>
    <ProdID>0</ProdID>
    <ISVSVN>0</ISVSVN>
    <StackMaxSize>1048576</StackMaxSize>
    <HeapMaxSize>201326592</HeapMaxSize>
    <TCSNum>32</TCSNum>
    <TCSPolicy>1</TCSPolicy>
    <DisableDebug>0</DisableDebug>
    <MiscSelect>0</MiscSelect>
    <MiscMask>0xFFFFFFFF</MiscMask>
    <ReservedMemMaxSize>335544320</ReservedMemMaxSize>
    <ReservedMemMinSize>335544320</ReservedMemMinSize>
    <ReservedMemInitSize>335544320</ReservedMemInitSize>
    <ReservedMemExecutable>1</ReservedMemExecutable>
</EnclaveConfiguration>
tcs_num 32, tcs_max_num 32, tcs_min_pool 1
The required memory is 573083648B.
The required memory is 0x22289000, 559652 KB.
Succeed.
Built the Occlum image and enclave successfully
occlum run /bin/python3.7 demo.py
/opt/occlum/build/bin/occlum: line 191:   170 Illegal instruction     (core dumped) RUST_BACKTRACE=1 "$instance_dir/build/bin/occlum-run" "$@"
root@6b2a0e64849b:~/demos/python# 
```

**Comment by guzongmin** [comment]
@tahashmi Can you please try "occlum gdb /bin/python3.7 demo.py" to get more infomation about the crash?

**Comment by tahashmi** [comment]
Hi @guzongmin, Please have a look at the output log in running `occlum gdb /bin/python3.7 demo.py` instead of `occlum run /bin/python3.7 demo.py`

```
(base) tahmad@TUD256255:~$ sudo docker run -it --device /dev/isgx --name occ08 occlum/occlum:0.15.1-ubuntu18.04
root@ec75d99d2ea7:~# aesm_service[19]: [ADMIN]White List update requested
aesm_service[19]: The server sock is 0x561744cfc120
aesm_service[19]: [ADMIN]White list update request successful for Version: 79
^C
root@ec75d99d2ea7:~# ls
demos
root@ec75d99d2ea7:~# cd demos/python/
root@ec75d99d2ea7:~/demos/python# vi run_python_on_occlum.sh 
root@ec75d99d2ea7:~/demos/python# ./run_python_on_occlum.sh 
/root/demos/python/occlum_instance initialized as an Occlum instance
Enclave sign-tool: /opt/intel/sgxsdk/bin/x64/sgx_sign
Enclave sign-key: /opt/occlum/etc/template/Enclave.pem
SGX mode: HW
Building new image...
[+] Home dir is /root
[-] Open token file /root/enclave.token error! Will create one.
[+] Init Enclave Successful 446676598786!
Building libOS...
EXPORT => OCCLUM_BUILTIN_CONF_FILE_MAC = f4-02-a0-4b-42-4e-22-c0-5e-29-b2-4b-dc-08-f2-53
EXPORT => OCCLUM_BUILTIN_VM_USER_SPACE_SIZE = 335544320
Signing the enclave...
<EnclaveConfiguration>
    <ProdID>0</ProdID>
    <ISVSVN>0</ISVSVN>
    <StackMaxSize>1048576</StackMaxSize>
    <HeapMaxSize>201326592</HeapMaxSize>
    <TCSNum>32</TCSNum>
    <TCSPolicy>1</TCSPolicy>
    <DisableDebug>0</DisableDebug>
    <MiscSelect>0</MiscSelect>
    <MiscMask>0xFFFFFFFF</MiscMask>
    <ReservedMemMaxSize>335544320</ReservedMemMaxSize>
    <ReservedMemMinSize>335544320</ReservedMemMinSize>
    <ReservedMemInitSize>335544320</ReservedMemInitSize>
    <ReservedMemExecutable>1</ReservedMemExecutable>
</EnclaveConfiguration>
tcs_num 32, tcs_max_num 32, tcs_min_pool 1
The required memory is 573083648B.
The required memory is 0x22289000, 559652 KB.
Succeed.
Built the Occlum image and enclave successfully
occlum gdb /bin/python3.7 demo.py
GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Source directories searched: /opt/intel/sgxsdk/lib64/gdb-sgx-plugin:$cdir:$cwd
Setting environment variable "LD_PRELOAD" to null value.
Reading symbols from /root/demos/python/occlum_instance/build/bin/occlum-run...(no debugging symbols found)...done.
(gdb) run
Starting program: /root/demos/python/occlum_instance/build/bin/occlum-run /bin/python3.7 demo.py
warning: Error disabling address space randomization: Operation not permitted
detect urts is loaded, initializing
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
add-symbol-file '/root/demos/python/occlum_instance/build/lib/libocclum-libos.signed.so' 0x7f43c0017040 -s .interp 0x7f43c00002e0  -s .note.gnu.build-id 0x7f43c00002fc  -s .gnu.hash 0x7f43c0000320  -s .dynsym 0x7f43c0000350  -s .dynstr 0x7f43c00003c8  -s .gnu.version 0x7f43c0000416  -s .gnu.version_d 0x7f43c0000420  -s .rela.dyn 0x7f43c0000458  -s .plt 0x7f43c0017000  -s .plt.got 0x7f43c0017010  -s .nipx 0x7f43c0168440  -s .rodata 0x7f43c0169000  -s .niprod 0x7f43c0189180  -s .builtin_config 0x7f43c0189a40  -s .eh_frame_hdr 0x7f43c0189a70  -s .eh_frame 0x7f43c01909e0  -s .gcc_except_table 0x7f43c01b9a64  -s .tbss 0x7f43c01c66e0  -s .fini_array 0x7f43c01c66e0  -s .data.rel.ro 0x7f43c01c6740  -s .dynamic 0x7f43c01d3d58  -s .got 0x7f43c01d3ee8  -s .data 0x7f43c01d5000  -s .nipd 0x7f43c01d5310  -s .bss 0x7f43c01d5320 
[New Thread 0x7f443b010700 (LWP 184)]
add-symbol-file 'image/lib/ld-musl-x86_64.so.1' 0x7f43d0e142f0 -s .hash 0x7f43d0e00190  -s .gnu.hash 0x7f43d0e02c48  -s .dynsym 0x7f43d0e05f08  -s .dynstr 0x7f43d0e0fe80  -s .rela.dyn 0x7f43d0e13bb8  -s .rela.plt 0x7f43d0e14218  -s .plt 0x7f43d0e14290  -s .rodata 0x7f43d0e5d700  -s .eh_frame_hdr 0x7f43d0e912c8  -s .eh_frame 0x7f43d0e912f8  -s .data.rel.ro 0x7f43d1091c40  -s .dynamic 0x7f43d1091e20  -s .got 0x7f43d1091f70  -s .got.plt 0x7f43d1092000  -s .data 0x7f43d1092040  -s .bss 0x7f43d10924a0 
add-symbol-file 'image/bin/python3.7' 0x7f43d0df6060 -s .interp 0x7f43d0df5270  -s .gnu.hash 0x7f43d0df5290  -s .dynsym 0x7f43d0df52d8  -s .dynstr 0x7f43d0df5458  -s .rela.dyn 0x7f43d0df5548  -s .rela.plt 0x7f43d0df55d8  -s .init 0x7f43d0df6000  -s .plt 0x7f43d0df6010  -s .plt.got 0x7f43d0df6040  -s .fini 0x7f43d0df61c9  -s .eh_frame_hdr 0x7f43d0df7000  -s .eh_frame 0x7f43d0df7028  -s .ctors 0x7f43d0df8e00  -s .dtors 0x7f43d0df8e10  -s .dynamic 0x7f43d0df8e20  -s .got 0x7f43d0df8fb0  -s .data 0x7f43d0df9000  -s .bss 0x7f43d0df9020 

Thread 1 "occlum-run" received signal SIGILL, Illegal instruction.
__exec_task () at src/process/task/task_x86-64.S:62
62	src/process/task/task_x86-64.S: No such file or directory.
(gdb) 

```

**Comment by tahashmi** [comment]
I am able to run this Python demo. 
I have uninstalled and installed again `enable_rdfsbase` kernel module and changed `resource_limits.kernel_space_heap_size = "192MB"`.  Closing this issue. 

Thanks @tatetian and @guzongmin
